### PR TITLE
removing deprecations for atom editor update

### PR DESCRIPTION
**Pull request by cjwilburn**
this should fix the Package.loadSettings warning in atom

### CODE REVIEW

**Comment by RobLoach** [comment]
:+1: Thanks @cjwilburn... Are there any other updates required to go through to keep it up to date? I saw the discussion in the Atom thread too.

**Comment by cjwilburn** [comment]
@RobLoach I don't think any are required right now. The plugin seems to otherwise work fine. Publishing should make sure that the changes take effect.

**Comment by RobLoach** [comment]
@cjwilburn Thanks again. Published and out on 0.4.2.

**Comment by cjwilburn** [comment]
No problem. Sounds good.

**Pull request merged**
